export const FETCHING_MASTERNODE_LIST = "FETCHING_MASTERNODE_LIST";
export const FETCHING_MASTERNODE_LIST_SUCCESS = "FETCHING_MASTERNODE_LIST_SUCCESS";
export const FETCHING_MASTERNODE_LIST_FAIL = "FETCHING_MASTERNODE_LIST_FAIL";

export const FETCHING_GETINFO = "FETCHING_GETINFO";
export const FETCHING_GETINFO_SUCCESS = "FETCHING_GETINFO_SUCCESS";
export const FETCHING_GETINFO_FAIL = "FETCHING_GETINFO_FAIL";